# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      matrix:
        r-version: ['4.2.1']
        config:
          - {os: macOS-10.15, r: 'release'}
          - {os: macOS-11, r: 'release'}
          - {os: macOS-12, r: 'release'}
          - {os: ubuntu-latest, r: 'release'}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1'
      - name: Install libcurl on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          install.packages("rcmdcheck")
          install.packages("remotes")
          remotes::install_deps(dependencies=TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args="--no-manual", error_on="error")
        shell: Rscript {0}
